services:
- type: web
  name: telegram-schedule-bot
  plan: free
  runtime: python
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
  autoDeploy: true
  envVars:
  - key: BOT_TOKEN
    sync: false
  - key: WEBHOOK_URL
    sync: false
  - key: PORT
    value: 8000
  - key: TZ
    value: Asia/Tbilisi