services:
- type: web
  name: telegram-schedule-bot
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
  plan: free
  autoDeploy: true
  envVars:
  - key: BOT_TOKEN
    sync: false
  - key: TIMEZONE
    value: UTC
  - key: PORT
    value: 8000